'use client';

import { useEffect, useMemo, useState } from 'react';

interface PetIdCardDownloadProps {
  pet: any;
}

function buildPetIdCode(rawId: string | undefined) {
  const cleaned = String(rawId || '').replace(/[^a-zA-Z0-9]/g, '').toUpperCase();
  const segment = cleaned.slice(-8).padStart(8, '0');
  return `PT-${segment}`;
}

function safeText(value: unknown, fallback = 'N/A') {
  const text = String(value ?? '').trim();
  return text || fallback;
}

function loadImage(url: string) {
  return new Promise<HTMLImageElement>((resolve, reject) => {
    const image = new Image();
    image.crossOrigin = 'anonymous';
    image.onload = () => resolve(image);
    image.onerror = () => reject(new Error('Failed to load image'));
    image.src = url;
  });
}

function drawFittedText(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  maxFontSize: number,
  minFontSize: number,
  weight: '400' | '700' = '700'
) {
  let size = maxFontSize;
  while (size >= minFontSize) {
    ctx.font = `${weight} ${size}px Arial`;
    if (ctx.measureText(text).width <= maxWidth) break;
    size -= 2;
  }
  ctx.fillText(text, x, y);
}

export function PetIdCardDownload({ pet }: PetIdCardDownloadProps) {
  const [cardDataUrl, setCardDataUrl] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);

  const petIdCode = useMemo(() => buildPetIdCode(pet?.id), [pet?.id]);
  const imageUrl = useMemo(() => {
    const mediaUrls = pet?.post?.media_urls;
    if (Array.isArray(mediaUrls) && mediaUrls.length > 0) {
      return String(mediaUrls[0]);
    }
    return '';
  }, [pet?.post?.media_urls]);

  useEffect(() => {
    let active = true;

    const generateCard = async () => {
      setIsGenerating(true);

      const canvas = document.createElement('canvas');
      canvas.width = 960;
      canvas.height = 600;
      const ctx = canvas.getContext('2d');

      if (!ctx) {
        setIsGenerating(false);
        return;
      }

      ctx.fillStyle = '#f8fafc';
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      ctx.fillStyle = '#dbeafe';
      ctx.fillRect(0, 0, canvas.width, 130);

      ctx.fillStyle = '#1f2937';
      ctx.font = '700 44px Arial';
      ctx.fillText('PAWTOPIA PET ID CARD', 30, 70);
      ctx.font = '400 24px Arial';
      ctx.fillText('Verified Companion Identity', 30, 102);

      ctx.strokeStyle = '#94a3b8';
      ctx.lineWidth = 4;
      ctx.strokeRect(30, 150, 270, 360);

      let drewImage = false;
      if (imageUrl) {
        try {
          const image = await loadImage(imageUrl);
          if (active) {
            ctx.drawImage(image, 40, 160, 250, 340);
            drewImage = true;
          }
        } catch {
          drewImage = false;
        }
      }

      if (!drewImage) {
        ctx.fillStyle = '#e2e8f0';
        ctx.fillRect(40, 160, 250, 340);
        ctx.fillStyle = '#64748b';
        ctx.font = '700 60px Arial';
        ctx.fillText('PET', 105, 340);
      }

      const name = safeText(pet?.name, 'Unnamed Pet');
      const species = safeText(pet?.species);
      const breed = safeText(pet?.breed);
      const sex = safeText(pet?.gender).toUpperCase();
      const size = safeText(pet?.size).toUpperCase();

      ctx.fillStyle = '#111827';
      ctx.font = '400 30px Arial';
      ctx.fillText('Name', 340, 210);
      drawFittedText(ctx, name, 340, 265, 300, 54, 34, '700');

      ctx.font = '400 30px Arial';
      ctx.fillText('Breed', 340, 330);
      drawFittedText(ctx, breed, 340, 382, 300, 50, 30, '700');

      ctx.font = '400 30px Arial';
      ctx.fillText('Species', 340, 445);
      drawFittedText(ctx, species, 340, 495, 300, 44, 28, '700');

      ctx.font = '400 30px Arial';
      ctx.fillText('Pet ID', 660, 210);
      drawFittedText(ctx, petIdCode, 660, 265, 270, 56, 30, '700');

      ctx.font = '400 30px Arial';
      ctx.fillText('Sex', 660, 330);
      drawFittedText(ctx, sex, 660, 382, 270, 50, 30, '700');

      ctx.font = '400 30px Arial';
      ctx.fillText('Size', 660, 445);
      drawFittedText(ctx, size, 660, 495, 270, 44, 28, '700');

      ctx.fillStyle = '#e2e8f0';
      ctx.fillRect(0, 548, canvas.width, 52);
      ctx.fillStyle = '#334155';
      ctx.font = '400 20px Arial';
      ctx.fillText('Generated by Pawtopia. Present this card as your pet profile identity reference.', 30, 582);

      if (!active) return;

      try {
        setCardDataUrl(canvas.toDataURL('image/png'));
      } catch {
        setCardDataUrl('');
      } finally {
        setIsGenerating(false);
      }
    };

    generateCard();

    return () => {
      active = false;
    };
  }, [imageUrl, pet?.breed, pet?.gender, pet?.id, pet?.name, pet?.size, pet?.species, petIdCode]);

  const handleDownload = () => {
    if (!cardDataUrl) return;

    const anchor = document.createElement('a');
    anchor.href = cardDataUrl;
    anchor.download = `${petIdCode}.png`;
    anchor.click();
  };

  return (
    <div className="rounded-xl border border-gray-200 bg-white p-3">
      <div className="flex items-center justify-between gap-3 mb-2">
        <p className="text-sm font-semibold text-gray-800">Pet ID: {petIdCode}</p>
        <button
          type="button"
          onClick={handleDownload}
          disabled={!cardDataUrl || isGenerating}
          className="px-3 py-1.5 text-xs font-semibold rounded-lg bg-primary-600 text-white hover:bg-primary-700 disabled:opacity-60"
        >
          {isGenerating ? 'Generating...' : 'Download PNG'}
        </button>
      </div>

      <div className="w-full aspect-[8/5] rounded-lg border border-gray-200 bg-white overflow-hidden">
        {cardDataUrl ? (
          <img src={cardDataUrl} alt="Generated pet ID card" className="w-full h-full object-contain" />
        ) : (
          <div className="w-full h-full bg-gray-100 animate-pulse" />
        )}
      </div>
    </div>
  );
}
