import {
  getBranchAvailabilitySlots,
  createHealthcareAppointmentRequest,
  createHealthcareSlot,
  getAvailableHealthcareSlots,
  getDvmfBranchProfile,
  getDvmfHealthcareBranches,
  getDvmfHealthcareAppointmentRequests,
  getDvmfHealthcareCalendar,
  getDvmfHealthcareCalendarWeek,
  getDvmfHealthcareServicesForOwner,
  getHealthcareEligiblePets,
  getHealthcareServices,
  initiateMayaCheckout,
  getMyHealthcareAppointmentRequests,
  removeDvmfHealthcareService,
  reviewHealthcareAppointmentRequest,
  saveDvmfHealthcareService,
  updateDvmfBranchProfile,
} from '@/lib/actions/healthcare.actions';
import { createActionRoute } from '@/lib/server/api/action-route';

export const POST = createActionRoute({
  getHealthcareServices,
  getDvmfHealthcareBranches,
  getHealthcareEligiblePets,
  getAvailableHealthcareSlots,
  getBranchAvailabilitySlots,
  createHealthcareAppointmentRequest,
  getMyHealthcareAppointmentRequests,
  getDvmfHealthcareAppointmentRequests,
  reviewHealthcareAppointmentRequest,
  createHealthcareSlot,
  getDvmfHealthcareCalendarWeek,
  getDvmfHealthcareCalendar,
  getDvmfHealthcareServicesForOwner,
  saveDvmfHealthcareService,
  removeDvmfHealthcareService,
  getDvmfBranchProfile,
  updateDvmfBranchProfile,
  initiateMayaCheckout,
});
